#microfrontend chat
ec.com.technoloqie.chatbot.app.url=${TEC_CHATBOT_APP_URL}

#RabbitMQ - conexion externa (US-01)
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.ssl.enabled=${RABBITMQ_SSL_ENABLED:false}